apiVersion: v1
kind: Pod
metadata:
  name: limitrangesuccesspod
  namespace: mynamespace1
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      limits:
        #defined resource limits for the container, which specify the maximum amount of resources that the container can use
        cpu: 400m
        memory: 400Mi
      requests:
        cpu: 200m
        memory: 200Mi
