apiVersion: v1
kind: LimitRange
metadata:
  name: podlimitrange
  namespace: mynamespace1
spec:
  limits:
  - type: Container
    default:
      #if we do not specify the resource limits in the pod spec, then these values will be used
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      #if we do not specify the resource requests in the pod spec, then these values will be used
      cpu: "250m"
      memory: "256Mi"
