apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: firstrs
spec:
  replicas: 2
  selector:   #here we need to specify the label selector to match the pods that belong to this ReplicaSet
    matchLabels:
      app: myapp
  template: #here we define the pod template that will be used to create the pods managed by this ReplicaSet
    metadata:
      labels: #here we define the labels that will be applied to the pods created by this ReplicaSet
        app: myapp
    spec: #specs related to the pod template, such as containers, volumes, etc.
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80