apiVersion: v1
kind: ResourceQuota
metadata:
  name: myresourcequota
  namespace: mynamespace1
spec:
  hard:
    requests.cpu: "4" #maximum amount of CPU that can be requested by all pods in the namespace
    requests.memory: "8Gi" #maximum amount of memory that can be requested by all pods in the namespace
    limits.cpu: "8" #maximum amount of CPU that can be limited by all pods in the namespace
    limits.memory: "16Gi" #maximum amount of memory that can be limited by all pods in the namespace
