apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efsstorage #define the storage class name here, given in storageclass.yml
  resources:
    requests:
      storage: 5Gi
