apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efsstorage
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-09bf2e686a7b5e017

#attach efs-driver-policy to the IAM role of the worker node group
